# PYTHON COURSE FOR SCIENTIFIC PROGRAMMING 
**Contributors:** \
Artur Llabrés Brustenga: Artur.Llabres@e-campus.uab.cat \
Gerard Navarro Pérez: Gerard.NavarroP@e-campus.uab.cat \
Arnau Parrilla Gibert: Arnau.Parrilla@e-campus.uab.cat \
Jan Scarabelli Calopa: Jan.Scarabelli@e-campus.uab.cat \
Xabier Oyanguren Asua: Xabier.Oyanguren@e-campus.uab.cat

Course material can be found at: https://llacorp.github.io/Python-Course-for-Scientific-Programming/ 

# LECTURE V : File manipulation

- Files may be used to save all processed/generated data in each execution. 
- Broadly speaking, we will distinguish two types of them: text and binary.
- We will learn some of the most common functions to manipulate files using Python.
- Despite each OS has its own system to create and access files, Python is independent of it as it uses a common interface known as a "file handle".

## 1. File Handing

### (a) Open


The key function for working with files in Python is the `open()` function. It takes two parameters: `filename`, and `mode`.

There are four different methods (modes) for opening a file:

| Indicator (naive/extra) | Open a file to... | Opening mode + | Pointer Position |
| --- | --- | --- | --- |
| r/r+ | Read it. | +writing | Beginning |
| w/w+ | Write on it. It **overwrites** the file if it already existed. Creates a new file otherwise | +reading | Beginning |
| x/x+ | Write on it. `FileExistsError` raised and execution will stop if it already existed (safe mode). Creates a new file otherwise | +reading | Beginning | 
| a/a+ | Write at the end of an already existing file if it exists. Creates a new file otherwise. | +reading | End

(In general, it is my advice to use the "no +" modes of operation, to a void confusions.)

Let's see an example. We want to open a file called `"File.txt"` in `"w"` mode. That is, we want to create a new file with that name or just overrite any file with such a name with the objective of writting data to it.

In [2]:
nameHandle = open("File.txt","w")

where:
- `nameHandle` stands for the name we have invented to handle this file. That is, it will be our "access" to the file. If we want to write data to this file we will tell this object to do so.
- `open()` is the function to open a file, as we have already said.
- `"File.txt"` is the name (string) of the file we want to open.
- `"w"` indicates we want to write on this file (in an overwritting way).

##### Note on Encodings
As a side note, remember that everything in the end (in the memeory of the computer) is saved and manipulated in bits (0-s and 1-s), this means that in reality in the memory of the computer there is nowhere a letter `a`. Instead if for example we want to encode the 27 characters of the alphabet, we could give each letter a unique tag using sequences of 5 bits (there are 32 possible sequences since $2^5=32$). If so, we could say `a` will be the sequence $00000$, `b` will be $00001$, `c` will be $00010$ etc. Such that in memory we will save the text `acb` as $000000001000001$. Then when we want to read it again, we will need to specify in which encoding the text is codified to be able to convert it back to characters.

One of the first encoding standards for text was the so called ASCII standard based on the alphabet and symbols for English, which used 7 bits to encode about 127 different symbols or characters, among them the alphabetic characters, the numerical digits, symbols like `?` or `!` and some other special characters like `\n` representing line breaks, or some representing the end of a text file among others.

Today there are several standardized encodings, and each operative system (OS) has its preferred ones. ASCII was the main encoding used in Internet until December 2007, when it was surpassed by UTF-8 using 8 bits (and thus allowing double symbols to be coded).

In the function `open()`, we can also add a thrid argument indicating the **encoding** for the characters we will deal with in this file. If we do not specify it, Python will just use the default encoding on the OS. But in general, we could specify any of the encodings listed in the following table of the official Python documentation:

[https://docs.python.org/3/library/codecs.html#standard-encodings](https://docs.python.org/3/library/codecs.html#standard-encodings)

for example we could write `'utf_8'` or `'ascii'` as a third argument, say:

`open("File.txt", "w", "utf_8) `


### (b) Write and Close

The file handle we have created (the variable we decided to call `fileHandle`) is in reality an object with a pointer to a specific position of the text file. You can imagine it as the **cursor** that appears when you are writting something on a computer, just that this time you cannont see where the cursor is (it is this what we called "Pointer position" in the first table of the lecture).

Now, this file handle is like a variable, but which not only contains information, it also has associated functions that allow the user to do multiple things to the file pointed by the handle (it is a class instance, as we will comment in the end of the lecture). One of these functions is `.write()`. The string we pass to it as an argument will be written to the file in the last position we have added something (in the position of the cursor). That is, we can call to it multiple times and the added text will be sequential in the file.

After manipulating the file, we **must** call to the `.close()` function! It is then when the text is really written to the file. Until then, there might be parts of the text we have sent using `.write()` that were left floating in a limbo (called a text **buffer**).

Let's see an example.

In [2]:
fileHandle = open("File.txt","w") #Creation of the file
fileHandle.write("Hi!\nWelcome to the python course.\n")
fileHandle.write("Enjoy!\n")
fileHandle.close()

If you now open the file "File.txt" that has been created in the directory where the Jupyter Notebook is, you will see that it contains the follwoing text:

You may have noticed the strange character `\n` we introcuced in the writting function as part of the string. The character `\` is an escapement character, meaning that the following character must be treated in a speacial way. In this case, for example, the string `\n` indicates the beginning of a new line. Another example is `\t` which will be interpreted as a TAB space.

Or for example, imagine we would like to write a double or single quote `"` or `'` to the file. How could we do this? Since they are the string delimiters in Python we will find it to be impossible. Try it. For this, we have the special characters `\"` and `\'` respectively!

Once again, after having edited the file, we want to save the changes to let other programmes access its contents. To do so, we must use the `.close()` function.


#### Notes on Relative and Absolute Paths
As we said, the result of this operation will be the creation of the file in the same directory (**directory==folder**) as the Jupyter Notebook is saved. But, is it possible to create files in other locations? Absolutely! 

For that instead of just introducing the name of the file in `open()` as `"File.txt"` we will need to introduce the details of the **path** to the directory we want it to be saved. The path is the location of a file or directory in the tree of directories of the persistent memory of the computer. We can provide it in two ways. A **relative path** is a path given from the point the Python interpreter is being executed and on (in our case, from the directory of the Jupyter Notebook and down there). For instance, imagine you have the following tree of directories under the folder where this Jupyter Notebook called Lecture_05.ipynb is:

Then, if we want to save the text in the folder "Save_the_text_here_Folder" under the folder "Folder_1" which is insider the "Python_Course" folder where this notebook is, you will do:

`open("Folder_1/Save_the_texts_here_Folder/File.txt", "w")`

This path `"Folder_1/Save_the_texts_here_Folder/File.txt"` is the a so called relative path.

If instead you want to save things anywhere in the directory structure, we will need to write the full path from the beginning of the tree of folders, for example something like `"/home/xabier/Documents/UAB/My_texts/File.txt"`. This is called an **absolute path**, since there is no doubt where I am trying to save it. That is, even if I move the Jupyter Notebook to other places in memory, the text file will always be created in the same place! 

Ofcourse, this will work if those folders like `"Folder_1"` or `"Documents"` etc. already exist! Make sure they do. We will see in a moment how to create new directories using Python.

##### Important note for Windows vs Linux/MacOS users
In Linux and MacOS, the directory structure always starts in a `"/"` and the next subfolders are indicated with a bar `"/"`, like `"/home/xabier/Documents/UAB/My_texts/File.txt"`. However, in Windows directory trees always start in the drive in which data is saved, typically `"C:\` and the separation between subdirectories is specified with an inverse bar `"\"`. For example `"C:\Users\xabier\Documents\UAB\My_texts\File.txt"`.

##### Comment on File names
If you really are into jumping from the naive user side to a more advanced computer user side, you should end today naming files with spaces and strange characters. This is because many interpreters (not the case of Python, but you will save problems in the future) interpret the space as a finish mark and will stop reading the name of the file at that poingt. That is, avoid naming files as `"¡My first text file is sugoi!.txt"` and instead name it `"My_first_text_file_is_sugoi.txt"` or something of the like.

In [ ]:
Zelan sortu direktorixoak etab despues de lo del texto!

To create a file in another location, we can use $\texttt{pathlib}$ library to know our current location and change it for the location we want to save the file in. On the other hand, $\texttt{os}$ library allows us to works with files nd directories of our Operative System.

Note: If needed you can install the libraries by executing $\texttt{pip install os}$ and $\texttt{pip install pathlib}$.

In [3]:
import os
import pathlib

path = pathlib.Path().absolute()
print(path)

try:
    os.mkdir("aux_directory/")
    print("The directory has been created succesfully!")

except FileExistsError as exc:
    print(exc)

/home/janska/Documents/UAB/PythonCourse/Theory
The directory has been created succesfully!


In [4]:
new_path = str(path) + "/aux_directory/"

fileHandle = open(new_path + "File.txt","w")
fileHandle.write("This file is located in a diferent location\n")
fileHandle.close()

It is possible to create files and directories in previous locations as well:

In [5]:
new_path = "/home/janska/Documents/UAB/auxPythonCourse/"

try:
    os.mkdir(new_path)
    print("The directory has been created succesfully!")

except FileExistsError as exc:
    print(exc)

[Errno 17] File exists: '/home/janska/Documents/UAB/auxPythonCourse/'


In [6]:
fileHandle = open(new_path + "File.txt","w")
fileHandle.write("This file is located in another diferent location: auxPythonCourse\n")
fileHandle.close()

### (c) Read

As we had the function `.write()` we also have the instruction `.read()`, which if the file is opened in read mode, allows us to read the content of a file (remember the encoding argument in case the read text looks non-sense). 

Calling `.read()` will output a string which will be the text of the file. We can save it to a variable for further processing, or just display it with `print()`.

Let's see the following example

In [7]:
fileHandle = open("File.txt","r") #read only
print(fileHandle.read())
fileHandle.close()

Hi!
Welcome to the python course.
Enjoy!



Yes, even when reading it is convenient to use the `.close()` function when we are done, even if in this case, it is usually save to have multiple readers reading the same file.

Note that if the text file was very big (like tens of gigabytes, it is not the most typical thing however), reading the whole file at once could be problematic. Instead, the `.read()` function accepts an integer argument indicating the number of characters we want to read from the file:

In [8]:
fileHandle = open("File.txt","r") #read only
print(fileHandle.read(5))
fileHandle.close()

Hi!
W


Then, if we asked another 5 characters before closing the file, we would receive the following 5. This is because the **cursor** of this particular handle will have moved on 5 positions.

In [ ]:
fileHandle = open("File.txt","r") #read only
print(fileHandle.read(5))
print("well well")
print(fileHandle.read(5))
fileHandle.close()

Don't forget you could save the read string to a variable!

In [ ]:
fileHandle = open("File.txt","r") #read only
text = fileHandle.read(5)

text = text + fileHandle.read(5)
print(text)
fileHandle.close()

Now, we can iterate over a file as well. A file will be interpreted as a list of strings where each element is a line of the file (the different parts separated by `\n`-s).

Consequently, we can use a `for()` loop to iterate over the lines of the file:

In [9]:
fileHandle = open("File.txt","r")

for line in fileHandle:
    print(line)
    
fileHandle.close()

Hi!

Welcome to the python course.

Enjoy!



Notice the blank line between lines. This is because each of the `line`-s in each iteration is a string with the line of the text with a `\n` at the end of the string, so when we print the line an extra new-line is printed, because the `print()` statement generates a new line for default.

As each `line` is a string, it is possible to avoid the `'\n'` by not taking the last character of the string.

In [10]:
fileHandle = open("File.txt","r")
for line in fileHandle:
    print(line[:-1])
fileHandle.close()

Hi!
Welcome to the python course.
Enjoy!


In [ ]:
fileHandle = open("File.txt","r")
for line in fileHandle:
    line = line[:-1] + 'xDD'
    print(line)
fileHandle.close()

#### Readline

The `.readline()` function allows us to read just one line, without the need of iterations. Which line will be read will depend on the cursor's current position.

In [11]:
fileHandle = open("File.txt","r")
one = fileHandle.read(5)
two = fileHandle.readline()
three = fileHandle.readline()
print(f"{one} \n {two} \n {three}")
fileHandle.close()

Hi!



#### Readlines

This functions returns a list of strings containing all the lines of the file in order:

In [13]:
fileHandle = open("File.txt","r")
list_of_lines = fileHandle.readlines()
fileHandle.close()

print(list_of_lines)

['Hi!\n', 'Welcome to the python course.\n', 'Enjoy!\n']


If we wanted to print only a specific line in the file, let's say the second line, we could use the following instruction.

In [14]:
fileHandle = open("File.txt","r")
second_line = fileHandle.readlines()[1]
fileHandle.close()
print(second_line)

Welcome to the python course.



### (d) Append

Each time an existing file is opened with "w" mode, its content is **completely** overwritten and the `.write()` method will start writting from the beginning. To avoid it, we can use the append mode `"a"`. When we call `.write()` in this mode, the text will be written after the last line of the file, without overwritting anything.

As an example, we are going to modify the file using `"w"`, an then we are going to add another line without deleteing anything. 

In [15]:
print("Result in writting mode:")
#Overwrite file
fileHandle = open("File.txt","w") 
fileHandle.write("Everything has been erased!\n")
fileHandle.close()
#Print result of "w"
fileHandle = open("File.txt","r")
print(fileHandle.read())
fileHandle.close()

print("Result with append mode:")
#Use of "a"
fileHandle = open("File.txt","a")
fileHandle.write("Use \'a\' parameter to avoid overwriting it!")
fileHandle.close()
#Print result of "a"
fileHandle = open("File.txt","r")
print(fileHandle.read())
fileHandle.close()

Result in writting mode:
Everything has been erased!

Result with append mode:
Everything has been erased!
Use 'a' parameter to avoid overwriting it!


If the file did not exist `"a"` will create a new one, just like `"w"`.

Now, what if we do not want any file to be overwritten nor appended new data. If we only wnat to create new files, but we want to be stopped if we try to write a file with the same name as an already existing one, we can use the `"x"` mode.

In [16]:
#Should return error if file already exists
fileHandle = open("File.txt","x") 
fileHandle.write("Let's try x mode\n")
fileHandle.close()

FileExistsError: [Errno 17] File exists: 'File.txt'

In [17]:
fileHandle = open("File2.txt","x")  # it will create a new file if it does not aleready exist
fileHandle.write("Let's try x mode\n")
fileHandle.close()

### Delete a file or directory

Sometimes we may want to delete an existing file or directory because it is no longer needed. As before, the $\texttt{os}$ library helps us with that:

In [18]:
import os

try:
    os.remove("File2.txt")

except IOError:
    print("File not found.")

Similarly, an EMPTY directory can be deleted. Firstly create an empty one. To observe the changes along the code, there exists a function that allows us to know the subdirectories and files existing at a given path (current by default): $\texttt{os.listdir}$

In [19]:
import os

print("Before creating the empty directory:\n")
print(str(os.listdir())+'\n')
os.mkdir("empty_directory")

print("After creating the empty directory:\n")
print(os.listdir())


Before creating the empty directory:

['File.txt', 'aux_directory', 'SesionFive.ipynb', '.ipynb_checkpoints']

After creating the empty directory:

['File.txt', 'empty_directory', 'aux_directory', 'SesionFive.ipynb', '.ipynb_checkpoints']


See that the directory should have been created and ther run:

In [20]:
os.rmdir("empty_directory")
print(str(os.listdir()))

A possible way to delete a non-empty directory could be by using $\texttt{shutil}$ librarry:

In [22]:
import shutil

dir_path = str(pathlib.Path().absolute()) + "/aux_directory"

shutil.rmtree(dir_path)

### (f) Tell and Seek

Files save data in a sequential way, meaning that every time it is automatically written at the end of it. Despite that, there exists some methods that allow us to choose the position of the pointer and start writing in another place: seek(), and another function to know the exact position of the pointer: tell().

There are many ocasions in which we could need an instruction as seek(). For example, let's supose we want to read a specific part of a file. A possible way to do it would be:

In [48]:
fileHandle = open("File.txt","r")
fileHandle.seek(len(fileHandle.readlines()[0]))
print(fileHandle.read(17))
print(fileHandle.tell())
fileHandle.close()

Use 'a' parameter
45


### (g) With

In [1]:
with open("File.txt", "r") as fileHandle:
    print(fileHandle.read())

Everything has been erased!
Use 'a' parameter to avoid overwriting it!


In [ ]:
Ein adibide bat donde se abran multiples archivos y se editen todos simulataneamente! En plan ejemplo

## 2. Manipulate Directory Structures

In [ ]:
Ein adibide bat donde se listen todos los archivos de un directorio y se genere un dictionary del contenido de cada uno

## 3. Numpy

With numpy it is possible to read files in order to extract their information and build arrays to work with. Basically, we can work upon text files or .npy and .npz files, which turn to be more efficient when it comes to loading data from them. 

### Reading data from .txt files: .write() and .loadtxt()

Let's see text files first. To do so, let's create a new file in wich we will introduce example values. Important: for now, the values must be written as strings and not as integer, floats, etc. as they will be written in text files and the only datatype suported in them are $\texttt{char}$ or $\texttt{strings}$.

In [4]:
import numpy as np

In [9]:
with open("np.txt","w") as npHandle:
    npHandle.write("1 2 3")

Instead of $\texttt{read}()$ function, numpy uses $\texttt{loadtxt}()$ to read information from text files.

In [10]:
np.loadtxt("np.txt")

array([1., 2., 3.])

Also possible with multidimensional arrays, where the '\n' character will indicate by default the end of a row.

In [7]:
with open("np.txt","w") as npHandle:
    npHandle.write("1 0 0\n0 1 0\n0 0 1\n")

np.loadtxt("np.txt")

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Notice how the data is written in np.txt and how the loadtxt function reads it. We can change it by modifying some parameters. For example, imagine we want an array of integers and the data we recieve comes with de delimiter ',':

In [61]:
with open("npex.txt","w") as npHandle:
    npHandle.write("1,0,0\n0,1,0\n0,0,1\n")

np.loadtxt("npex.txt", dtype='int', delimiter=',')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

#### savetxt()

Until now we have been writing 'arrays' as strings in a text file, but with $\texttt{savetxt}()$ we can also save numpy arrays in a .txt or .csv file and they will be automatically converted to strings:

In [15]:
a = np.array([1,2,3])

np.savetxt("np.txt", a, delimiter=',') #default is ','

np.loadtxt("np.txt")

array([1., 2., 3.])

There are more useful parameters we can use to adapt the data to what we want. Let's see some of them.

##### skiprows and max_rows

In [16]:
np.savetxt("np.txt", np.identity(4))
np.loadtxt("np.txt")

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
np.loadtxt("np.txt", skiprows=1, max_rows=2)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.]])

##### usecols

In [78]:
np.loadtxt("npex.txt", usecols=[0,3])

array([[1., 0.],
       [0., 0.],
       [0., 0.],
       [0., 1.]])

##### ndmin (0 as default)

In [87]:
npHandle = open("npex.txt","w")
npHandle.write("1 2 3 4\n")
npHandle.close()

In [89]:
np.loadtxt("npex.txt")

array([1., 2., 3., 4.])

In [93]:
np.loadtxt("npex.txt", ndmin=2)

(1, 4)

### Reading data from .npy or .npz files

A .npy file is a binary file from which we extract the data we want to study, such as .txt files or .csv. The difference though, is that when talking about big datasets, .npy files result to be much more faster as they are binary files. An example of use is with datasets that are prepared to be used in machine learning algorithms.

Let's see how they work.

#### save() and load()

A numpy array can be saved into a .npy file by using $\texttt{save}()$ function, and it can be loaded with $\texttt{load}()$.

In [42]:
a = np.random.randint(low = 0, high = 100, size = (4,6))

np.save("npyfile.npy",a)
np.load("npyfile.npy")

array([[83,  7, 25,  0, 32, 33],
       [68, 10, 60, 38, 43, 77],
       [90, 91, 48, 41, 70, 67],
       [56, 83, 53, 94, 78, 39]])

On the other hand, we save data into a compressed .npz file with:

In [43]:
a = np.random.randint(low = 0, high = 100, size = (4,6))
b = np.random.randint(low = 0, high = 100, size = (4,6))

np.savez_compressed("npzfile.npz",a,b)
np.load("npzfile.npz")

As you can see, it does not print the array as expected. The reason of this is that $\texttt{load}()$ function for .npz files return a dictionary of arrays. To acces each of them, we can use $\textit{dict_data['arr_i']}$, where 'i' stands for the ith array:

In [44]:
data_dict = np.load("npzfile.npz")
print("First array:\n")
print(data_dict["arr_0"])

print("\nSecond array:\n")
print(data_dict["arr_1"])

First array:

[[92 42 81 13 29 87]
 [76 59  3 15 84 67]
 [ 9 26 84 29 27 88]
 [80 71 28 49  2 68]]

Second array:

[[66  2  0 27 13 33]
 [18 24 76 39 39 48]
 [37 65 94 49 81 31]
 [55 78 20 84 83 93]]


If you want to, you can see the difference by executing the next cells.

In [36]:
from time import time

In [10]:
Azaldu el time! Ein adibide bat en el que se vaya ejecutando algo y ke compruebe cada x tiempo tal.

SyntaxError: invalid syntax (<ipython-input-10-237fae4c8f7c>, line 1)

In [37]:
N = 10000000  # random datapoints
with open('data.txt', 'w') as data:
    for _ in range(N):
        data.write(str(10*np.random.random())+',')
data.close()

In [38]:
start = time()

with open('data.txt', 'r') as data:
    string_data = data.read()
    
end = time()
 
list_data = string_data.split(',')
list_data.pop()
data_array = np.array(list_data, dtype=float).reshape(10000, 1000)


print("### 10 million points of data ###")
print("\nData summary:\n", data_array)
print("\nData shape:\n", data_array.shape)
print(f"\nTime to read: {round(end-start,5)} seconds.")

### 10 million points of data ###

Data summary:
 [[4.09144984 3.84302398 7.16627551 ... 2.01428061 2.79600872 3.30568972]
 [2.56943462 1.89302601 0.32476652 ... 0.82489118 5.30315169 1.1540871 ]
 [7.37108472 0.90150474 6.49690544 ... 7.12834269 7.51508654 9.27592637]
 ...
 [9.36692545 2.33595017 1.21974856 ... 2.17260358 1.37939516 3.70853589]
 [8.78659462 1.00940435 0.25049989 ... 3.405163   5.45185069 6.97280555]
 [2.71625771 0.0726352  9.87130631 ... 3.27120981 3.12439974 4.9982651 ]]

Data shape:
 (10000, 1000)

Time to read: 0.12279 seconds.


Let's see the .npy version

In [40]:
np.save('data.npy', data_array)

In [41]:
start=time()

data_array = np.load('data.npy')

end=time()

print("### 10 million points of data ###")
print("\nData summary:\n", data_array)
print("\nData shape:\n", data_array.shape)
print(f"\nTime to read: {round(end-start,5)} seconds.")

### 10 million points of data ###

Data summary:
 [[4.09144984 3.84302398 7.16627551 ... 2.01428061 2.79600872 3.30568972]
 [2.56943462 1.89302601 0.32476652 ... 0.82489118 5.30315169 1.1540871 ]
 [7.37108472 0.90150474 6.49690544 ... 7.12834269 7.51508654 9.27592637]
 ...
 [9.36692545 2.33595017 1.21974856 ... 2.17260358 1.37939516 3.70853589]
 [8.78659462 1.00940435 0.25049989 ... 3.405163   5.45185069 6.97280555]
 [2.71625771 0.0726352  9.87130631 ... 3.27120981 3.12439974 4.9982651 ]]

Data shape:
 (10000, 1000)

Time to read: 0.0135 seconds.


For further information about numpy files, you can visit:

https://towardsdatascience.com/why-you-should-start-using-npy-file-more-often-df2a13cc0161

## Further topics

Apart from all functions and topics we've seen in the course, Python is a programming language that has many more utilities. Some of them could be:
- Object Oriented Programming
- Assertions and error controls
- Map and lambda functions
- Manipulating images, videos, sound.
- Machine Learning and Deep Learning
- ...